name: channel_talk_flutter
description: A plugin that translates the Channel Talk SDK into a plugin for Flutter(Unofficial)
version: 2.1.1
homepage: https://github.com/turlvo/channel_talk_flutter

environment:
  sdk: '>=2.13.4 <3.0.0'
  flutter: 2.2.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.deepnatural.channel_talk
        pluginClass: ChannelTalkFlutterPlugin
      ios:
        pluginClass: ChannelTalkFlutterPlugin


